# Generated by Django 5.0 on 2026-07-08 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('heart_rate', 'Rythme Cardiaque'), ('temperature', 'Température'), ('spo2', 'SpO2'), ('movement', 'Mouvement')], max_length=20)),
                ('severity', models.CharField(choices=[('warning', 'Avertissement'), ('critical', 'Critique')], max_length=20)),
                ('value_detected', models.DecimalField(decimal_places=2, help_text="Valeur mesurée ayant déclenché l'alerte", max_digits=6)),
                ('threshold_value', models.DecimalField(decimal_places=2, help_text='Seuil dépassé', max_digits=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Résolue'), ('false_alarm', 'Fausse Alerte')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patient')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('push', 'Push Notification'), ('email', 'Email')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Envoyée'), ('failed', 'Échouée'), ('delivered', 'Livrée')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert_notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['patient', '-created_at'], name='alerts_patient_bfcc80_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='alerts_status_0e4dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotificationlog',
            index=models.Index(fields=['alert', 'channel'], name='alert_notif_alert_i_2db456_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotificationlog',
            index=models.Index(fields=['recipient', 'status'], name='alert_notif_recipie_8f087a_idx'),
        ),
    ]
