# Generated by Django 4.2 on 2026-07-25 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('biometric_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricreading',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_readings', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='patients.patient'),
        ),
    ]
