# Generated by Django 4.2 on 2026-07-10 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hardware_id', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('firmware_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('unassigned', 'Non assigné'), ('active', 'Actif'), ('inactive', 'Inactif')], default='unassigned', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bracelet',
                'verbose_name_plural': 'Bracelets',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('battery_level', models.IntegerField()),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_status', to='devices.device')),
            ],
            options={
                'verbose_name': 'État du bracelet',
                'verbose_name_plural': 'États des bracelets',
                'db_table': 'device_status',
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='devices.device')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Association bracelet-patient',
                'verbose_name_plural': 'Associations bracelet-patient',
                'db_table': 'device_assignments',
            },
        ),
    ]
