# Generated by Django 4.2 on 2026-07-15 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceassignment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='patients.patient'),
        ),
    ]
