# Generated by Django 5.0 on 2026-07-08 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Nom complet du patient', max_length=255)),
                ('birth_date', models.DateField()),
                ('condition', models.CharField(choices=[('rheumatism', 'Rhumatisme'), ('other', 'Autre')], default='rheumatism', max_length=50)),
                ('threshold_heart_rate', models.IntegerField(help_text="Seuil d'alerte rythme cardiaque (bpm)")),
                ('threshold_temperature', models.DecimalField(decimal_places=1, help_text='Seuil température (°C)', max_digits=4)),
                ('threshold_spo2', models.IntegerField(help_text="Seuil d'alerte SpO2 (%)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text="Description de l'antécédent ou du diagnostic")),
                ('diagnosed_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Medical Histories',
                'db_table': 'medical_history',
                'ordering': ['-diagnosed_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientRelative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('child', 'Enfant'), ('spouse', 'Conjoint(e)'), ('sibling', 'Frère/Sœur'), ('friend', 'Ami(e)'), ('other', 'Autre')], default='other', max_length=50)),
                ('is_primary_contact', models.BooleanField(default=False, help_text="Contact d'urgence prioritaire")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='patients.patient')),
                ('relative_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patient Relatives',
                'db_table': 'patient_relatives',
                'unique_together': {('patient', 'relative_user')},
            },
        ),
    ]
